// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://undppzthskqsikywqvwn.supabase.co";
// Public anon/publishable key (safe to embed in frontend)
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZHBwenRoc2txc2lreXdxdnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTAxMTksImV4cCI6MjA3OTg4NjExOX0.Xlw3N2KvbSh5sO2H46wqwYJzwchoxrNNVduPuMV-STE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
